### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by paulzhang5511** [kataras/iris-cli#1]
**Describe the bug**
Run `iris-cli run `. An error occurred.
`
fork/exec /bin/sh: operation not permitted
`

**To Reproduce**
1. `iris-cli run`

**Expected behavior**
Run the project normally

**Screenshots**
![image](https://user-images.githubusercontent.com/53463972/72418177-500f2700-37b5-11ea-87ed-eb7c915d4f73.png)

**Desktop (please complete the following information):**
 - OS: ubuntu19.04
`
Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #476-Microsoft Fri Nov 01 16:53:00 PST 2019
`

**Additional context**

**Comment by kataras** [comment]
Hello @paulzhang5511, can you try with `sudo`?

**Comment by kataras** [comment]
Update: it's fixed (tested with docker ubuntu)
