### ISSUE TITLE
go get iris-cli error

### ISSUE THREAD

**Issue by raynerluo** [kataras/iris-cli#2]
rayner-mac:~ rayner$ go get github.com/kataras/iris-cli
go: finding github.com/kataras/iris-cli latest
go: downloading github.com/kataras/iris-cli v0.0.0-20200206040818-a782c6323472
go: extracting github.com/kataras/iris-cli v0.0.0-20200206040818-a782c6323472
go get: github.com/kataras/iris-cli@v0.0.0-20200206040818-a782c6323472 requires
	github.com/AlecAivazis/survey/v2@v2.0.0-00010101000000-000000000000: reading https://goproxy.io/github.com/%21alec%21aivazis/survey/v2/@v/v2.0.0-00010101000000-000000000000.mod: 404 Not Found

**Comment by kataras** [comment]
Thanks @raynerluo, it's fixed now!
