### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by 265525** [kataras/iris-cli#3]
I'm from China. I've already hung up my VPN and reported an error in iris cli new irisprotest basic：
When I type:iris-cli new iristest basic
Loading projects from <https://raw.githubusercontent.com/kataras/iris-cli/master/registry.yml>
Get "https://raw.githubusercontent.com/kataras/iris-cli/master/registry.yml": dial tcp 0.0.0.0:443: connect: connection refused

**Comment by kataras** [comment]
I see,  I can add a feature to our http client, which will try to proxy the request with multiple online (or local) proxy list, so you don't even need to run a VPN behind, I have it already in my plans but for the moment I must finish some other tasks first if that's ok with you.

**Comment by kataras** [comment]
Hello @265525 can you please try to update the package and run with `iris-cli --proxy=env new iristest basic` or `iris-cli --proxy=119.28.233.135:8080 new iristest basic`. Please write down if that is still failing. Thanks!
