### ISSUE TITLE
It is recommended to add a new project that can create a restful API structure

### ISSUE THREAD

**Issue by dafa168** [kataras/iris-cli#6]
**Is your feature request related to a problem? Please describe.**
建议新增可以新建一个restful api 结构的项目

```
command: $ iris-cli new [--module=my_app] api  
```

This creates a new API project and keeps the structure simple.

**Comment by dafa168** [comment]
Thank you !

**Comment by kataras** [comment]
Hello @dafa168, there is the `iris-cli new [--module=my_app] mvc` which creates [this project](https://github.com/iris-contrib/mvc-template). You need a new `api` template to handle the structure of raw iris.Handlers too. Stay tuned, I am on it!

**Comment by dafa168** [comment]
Okay thank you
