### ISSUE TITLE
iris-cli command not found error 

### ISSUE THREAD

**Issue by akaishingo** [kataras/iris-cli#7]
I've installed iris-cli on my system(ubuntu 21,Go version 1.17) using
`go install github.com/kataras/iris-cli@main`
When i try to run iris-cli i get
`iris-cli: command not found`
any idea about this?

**Comment by kataras** [comment]
HELLO @akaishingo,

Did you forgot to add the $GOPATH/bin to your PATH environment variable?

![image](https://user-images.githubusercontent.com/22900943/150211539-a86630fc-c31a-4b4c-af2f-f5273468f50d.png)

**Comment by akaishingo** [comment]
Thanks for your reply:)
I found that Ubuntu MATE 21 cannot load the path environment source file automatically, so I just installed the Ubuntu official version. now it works very well.
